#!/usr/bin/env bash
# Repo-wide style gate: no em dashes and no tool-attribution phrases in tracked
# files. This mirrors the lightweight project hygiene gate used by sibling
# repositories.

set -u

FAIL=0

# Em dash U+2014, built via printf so this script contains no em dash byte.
EMDASH=$(printf '\xe2\x80\x94')

is_enforcement_file() {
  case "$1" in
    .githooks/*|scripts/check-style.sh) return 0 ;;
    *) return 1 ;;
  esac
}

TOOL="Cla""ude"
PHRASES=(
  "Co-Authored-By: $TOOL"
  "Co-authored-by: $TOOL"
  "Generated with $TOOL"
  "Generated by $TOOL"
  "Powered by $TOOL"
  "as an AI"
)

while IFS= read -r f; do
  [ -f "$f" ] || continue
  if LC_ALL=C grep -qF -- "$EMDASH" "$f" 2>/dev/null; then
    echo "style: em dash (U+2014) in $f" >&2
    FAIL=1
  fi
  if ! is_enforcement_file "$f"; then
    for p in "${PHRASES[@]}"; do
      if LC_ALL=C grep -qF -- "$p" "$f" 2>/dev/null; then
        echo "style: forbidden attribution phrase in $f" >&2
        FAIL=1
      fi
    done
  fi
done < <(git ls-files)

if [ "$FAIL" -ne 0 ]; then
  echo "style: gate failed. See CONTRIBUTING.md." >&2
fi
exit "$FAIL"
